In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

cumleler = [
    "Kedi bahçede uyuyor.",
    "Bahçede bir kedi uyumakta.",
    "Otomobil motoru arızalandı."
]

vektorler = model.encode(cumleler)
print(vektorler.shape)

c:\Users\IamAh\anaconda3\envs\ahmedgpt\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\IamAh\anaconda3\envs\ahmedgpt\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\IamAh\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as

(3, 384)


In [5]:
print(model.similarity(vektorler, vektorler))

tensor([[ 1.0000,  0.9705, -0.0024],
        [ 0.9705,  1.0000,  0.0526],
        [-0.0024,  0.0526,  1.0000]])


In [7]:
import numpy as np

ic_carpim = np.dot(vektorler[0], vektorler[1])
uzunluk_a = np.linalg.norm(vektorler[0])
uzunluk_b = np.linalg.norm(vektorler[1])

benzerlik = ic_carpim / (uzunluk_a * uzunluk_b)

print(benzerlik)

0.9705463


In [8]:
bilgiler = [
    "Ahmed, Gazi Üniversitesi'nde Elektrik-Elektronik Mühendisliği 3. sınıf öğrencisidir.",
    "Ahmed üniversiteye diş hekimliğinde başladı, 2024'te Gazi EEE'ye geçiş yaptı.",
    "Ahmed'in ana ilgi alanı Edge AI ve gömülü yapay zeka; modelleri mikrodenetleyiciler gibi donanımlarda çalıştırmak istiyor.",
    "Ahmed gömülü sistemler üzerine bir mentorla çalışıyor ve C dilinde pointer konularında deneyim kazandı.",
    "Ahmed kariyerini ASELSAN, ROKETSAN ve TUSAŞ gibi savunma sanayii şirketlerinde yapmak istiyor.",
    "Ahmed yüksek lisansını Almanya'da yapmayı düşünüyor.",
    "Ahmed düzenli olarak spor salonuna gidiyor."
]

In [13]:
bilgi_vektorleri = model.encode(bilgiler)

soru = "Ahmed hangi üniversitede okuyor?"
soru_vektoru = model.encode([soru])

skorlar = model.similarity(soru_vektoru, bilgi_vektorleri)
print(skorlar)

en_iyi = skorlar[0].argmax()
print(bilgiler[en_iyi])

import torch

degerler, siralar = torch.topk(skorlar[0], k=3)
for skor, i in zip(degerler, siralar):
    print(f"{skor:.3f}  {bilgiler[i]}")

tensor([[0.6002, 0.5907, 0.3477, 0.5161, 0.5145, 0.5640, 0.6197]])
Ahmed düzenli olarak spor salonuna gidiyor.
0.620  Ahmed düzenli olarak spor salonuna gidiyor.
0.600  Ahmed, Gazi Üniversitesi'nde Elektrik-Elektronik Mühendisliği 3. sınıf öğrencisidir.
0.591  Ahmed üniversiteye diş hekimliğinde başladı, 2024'te Gazi EEE'ye geçiş yaptı.


In [14]:
bilgi_vektorleri = model.encode(bilgiler)

soru = "Ahmed'in en sevdiği film ne?"
soru_vektoru = model.encode([soru])

skorlar = model.similarity(soru_vektoru, bilgi_vektorleri)
print(skorlar)

en_iyi = skorlar[0].argmax()
print(bilgiler[en_iyi])

import torch

degerler, siralar = torch.topk(skorlar[0], k=3)
for skor, i in zip(degerler, siralar):
    print(f"{skor:.3f}  {bilgiler[i]}")

tensor([[0.3742, 0.2894, 0.3533, 0.3508, 0.4287, 0.3197, 0.4714]])
Ahmed düzenli olarak spor salonuna gidiyor.
0.471  Ahmed düzenli olarak spor salonuna gidiyor.
0.429  Ahmed kariyerini ASELSAN, ROKETSAN ve TUSAŞ gibi savunma sanayii şirketlerinde yapmak istiyor.
0.374  Ahmed, Gazi Üniversitesi'nde Elektrik-Elektronik Mühendisliği 3. sınıf öğrencisidir.
